name: ROS-CI
on: [push, pull_request]

jobs:
  CI:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic}
          - {ROS_DISTRO: noetic}
          - {ROS_DISTRO: humble}
          - {ROS_DISTRO: rolling}
    env:
      PRERELEASE: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}

